title: Joey Steele's Website
description: >- # this means to ignore newlines until "baseurl:"
  Joey Steele's website.
baseurl: ""
url: "joeysteele2001.github.io"
github_username: joeysteele2001

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  series:
    output: true


markdown: kramdown
kramdown:
  math_engine: katex
  math_engine_opts: {
    globalGroup: true, 
    macros: {
      "\\zero": "\\text{🥚}", 
      "\\one": "\\text{🦆}", 
      "\\idk": "?",
      "\\inv#1": "#1^{\\tiny -1}}"
    }
  }

highlighter: rouge

sass:
  style: compressed

exclude:
  - README.md
  - Makefile
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
